"use client";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Bot, Brain, FileText, GraduationCap, Target, Sparkles } from "lucide-react";
import { formatDistanceToNow } from "date-fns";

export default function WeeklyPlanCard({ plan }) {
  if (!plan) return null;

  const skills = Array.isArray(plan.skillFocus) ? plan.skillFocus : [];
  const tips = Array.isArray(plan.resumeTips) ? plan.resumeTips : [];

  const scoreColor =
    plan.readinessScore >= 70
      ? "text-green-500"
      : plan.readinessScore >= 40
        ? "text-amber-500"
        : "text-red-500";

  return (
    <Card className="border-indigo-500/20 bg-gradient-to-br from-indigo-500/5 to-violet-500/5">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-indigo-500" />
            This Week&apos;s Agent Plan
          </CardTitle>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-[10px] text-muted-foreground gap-1">
              <Bot className="h-2.5 w-2.5" />
              Generated by your career agent · updated weekly
            </Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-5">
        {/* Readiness Score */}
        <div className="flex items-center gap-4">
          <div>
            <p className="text-xs text-muted-foreground">Career Readiness</p>
            <div className="flex items-end gap-1.5">
              <span className={`text-3xl font-bold ${scoreColor}`}>
                {plan.readinessScore}
              </span>
              <span className="text-sm text-muted-foreground mb-0.5">/100</span>
            </div>
          </div>
          <Progress value={plan.readinessScore} className="flex-1 h-2" />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Skills to Focus */}
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              <Brain className="h-3 w-3" />
              Skills to Focus
            </p>
            <div className="space-y-1.5">
              {skills.map((s, i) => (
                <div key={i} className="rounded-lg border bg-background p-2.5">
                  <p className="text-sm font-medium">{s.skill}</p>
                  <p className="text-xs text-muted-foreground mt-0.5">{s.action}</p>
                  {s.resource && (
                    <p className="text-[10px] text-indigo-400 mt-0.5">{s.resource}</p>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Resume Tips */}
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              <FileText className="h-3 w-3" />
              Resume Tips
            </p>
            <div className="space-y-1.5">
              {tips.map((t, i) => (
                <div key={i} className="rounded-lg border bg-background p-2.5 flex items-start gap-2">
                  <Badge
                    variant="outline"
                    className={`text-[9px] shrink-0 mt-0.5 ${t.priority === "high" ? "border-red-300 text-red-500" : "border-amber-300 text-amber-500"}`}
                  >
                    {t.priority}
                  </Badge>
                  <p className="text-sm">{t.tip}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Interview Focus */}
          <div className="space-y-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              <GraduationCap className="h-3 w-3" />
              Interview Focus
            </p>
            <div className="rounded-lg border bg-background p-2.5">
              <p className="text-sm">{plan.interviewFocus}</p>
            </div>
            {plan.createdAt && (
              <p className="text-[10px] text-muted-foreground">
                Updated {formatDistanceToNow(new Date(plan.createdAt), { addSuffix: true })}
              </p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
